version: "3.9"

services:
  mongodb-express-example:
     image: mongo-express:latest
     container_name: mongodb-express-example
     ports:
       - "8081:8081"
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: Anandi
       ME_CONFIG_MONGODB_ADMINPASSWORD: Anandi
       ME_CONFIG_MONGODB_SERVER: mongodb-example
     networks:
       - network_example


networks:
  network_example:
    name: network_example
    driver: bridge
