version: "3.9"

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Anandi
      MONGO_INITDB_ROOT_PASSWORD: Anandi
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-example
    restart: always
    depends_on:
      - mongodb-example
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Anandi
      ME_CONFIG_MONGODB_ADMINPASSWORD: Anandi
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network_example

networks:
  network_example:
    driver: bridge
